// angular/invest-app/src/app/shared/components/investment-form/investment-form.component.ts
import { Component, computed, effect, inject, input, output, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import type { Investment, InvestmentType } from '../../models/investment.model';
import { formatCents, parseCents } from '../../utils/format';
import { optionalYieldValidator } from '../../utils/validators';
import { ModalComponent } from '../modal/modal.component';

const categoryLabels: Record<string, string> = {
  'Fixed Income': 'Renda Fixa',
  'Variable Income': 'Renda Variavel',
};

const todayISO = new Date().toISOString().split('T')[0];

@Component({
  selector: 'app-investment-form',
  imports: [ModalComponent, ReactiveFormsModule],
  template: `
    <app-modal [title]="investment() ? 'Editar investimento' : 'Novo investimento'" (close)="close.emit()">
      <form [formGroup]="form" (ngSubmit)="submit()" class="form-stack">
        <label class="field">
          <span>Nome</span>
          <input formControlName="name" placeholder="Ex: Tesouro IPCA+ 2045" />
          @if (showError('name')) {
            <small>Nome e obrigatorio</small>
          }
        </label>

        <div class="form-grid two">
          <label class="field">
            <span>Tipo</span>
            <select formControlName="typeId">
              @for (type of investmentTypes(); track type.id) {
                <option [value]="type.id">{{ type.name }}</option>
              }
            </select>
            @if (showError('typeId')) {
              <small>Tipo e obrigatorio</small>
            }
          </label>

          <label class="field">
            <span>Categoria</span>
            <input [value]="selectedCategoryLabel()" readonly />
          </label>
        </div>

        <div class="form-grid two">
          <label class="field">
            <span>Corretora</span>
            <input formControlName="broker" placeholder="Ex: XP Investimentos" />
            @if (showError('broker')) {
              <small>Corretora e obrigatoria</small>
            }
          </label>

          <label class="field">
            <span>Valor (R$)</span>
            <input
              [value]="amountDisplay()"
              inputmode="numeric"
              placeholder="0,00"
              (input)="changeAmount($event)"
            />
            @if (showError('amountCents')) {
              <small>Valor deve ser maior que zero</small>
            }
          </label>
        </div>

        <label class="field">
          <span>
            Rendimento
            <em>(opcional - ex: IPCA + 5%, 110% CDI, 100% Selic, 15%)</em>
          </span>
          <input formControlName="yield" placeholder="Ex: 100% Selic" />
          @if (form.controls.yield.hasError('yieldFormat')) {
            <small>Formatos aceitos: 15%, IPCA + 5%, 110% CDI, 100% Selic</small>
          }
        </label>

        <div class="form-grid two">
          <label class="field">
            <span>Data de aporte</span>
            <input type="date" formControlName="investedDate" />
            @if (showError('investedDate')) {
              <small>Data de aporte e obrigatoria</small>
            }
          </label>

          <label class="field">
            <span>Vencimento <em>(opcional)</em></span>
            <input type="date" formControlName="dueDate" />
          </label>
        </div>

        <div class="modal-actions">
          <button type="button" class="button button-outline" (click)="close.emit()">Cancelar</button>
          <button type="submit" class="button button-primary" [disabled]="!selectedType()">
            {{ investment() ? 'Salvar' : 'Cadastrar' }}
          </button>
        </div>
      </form>
    </app-modal>
  `,
})
export class InvestmentFormComponent {
  private readonly fb = inject(FormBuilder);

  readonly investment = input<Investment | null>(null);
  readonly investmentTypes = input.required<InvestmentType[]>();
  readonly save = output<Investment>();
  readonly close = output<void>();

  protected readonly amountDisplay = signal('');
  protected readonly form = this.fb.nonNullable.group({
    name: ['', [Validators.required]],
    typeId: ['', [Validators.required]],
    broker: ['', [Validators.required]],
    amountCents: [0, [Validators.required, Validators.min(1)]],
    yield: ['', [optionalYieldValidator]],
    investedDate: [todayISO, [Validators.required]],
    dueDate: [''],
  });

  protected readonly selectedType = computed(() => {
    const typeId = this.form.controls.typeId.value;
    return this.investmentTypes().find((type) => type.id === typeId) ?? this.investmentTypes()[0];
  });

  protected readonly selectedCategoryLabel = computed(() => {
    const category = this.selectedType()?.category;
    return category ? categoryLabels[category] : '';
  });

  constructor() {
    effect(() => {
      const investment = this.investment();
      const defaultType = this.investmentTypes()[0];

      if (investment) {
        this.form.reset({
          name: investment.name,
          typeId: investment.typeId,
          broker: investment.broker,
          amountCents: investment.amount,
          yield: investment.yield ?? '',
          investedDate: investment.investedDate,
          dueDate: investment.dueDate ?? '',
        });
        this.amountDisplay.set(formatCents(investment.amount));
        return;
      }

      this.form.reset({
        name: '',
        typeId: defaultType?.id ?? '',
        broker: '',
        amountCents: 0,
        yield: '',
        investedDate: todayISO,
        dueDate: '',
      });
      this.amountDisplay.set('');
    });
  }

  protected showError(controlName: keyof typeof this.form.controls) {
    const control = this.form.controls[controlName];
    return control.invalid && (control.dirty || control.touched);
  }

  protected changeAmount(event: Event) {
    const input = event.target as HTMLInputElement;
    const cents = parseCents(input.value);
    this.form.controls.amountCents.setValue(cents);
    this.form.controls.amountCents.markAsDirty();
    this.amountDisplay.set(formatCents(cents));
  }

  protected submit() {
    this.form.markAllAsTouched();
    const selectedType = this.selectedType();

    if (this.form.invalid || !selectedType) return;

    const data = this.form.getRawValue();
    this.save.emit({
      id: this.investment()?.id ?? crypto.randomUUID(),
      name: data.name,
      typeId: data.typeId,
      broker: data.broker,
      amount: data.amountCents,
      yield: data.yield || undefined,
      category: selectedType.category,
      investedDate: data.investedDate,
      dueDate: data.dueDate || null,
    });
  }
}

// classroom/app/invest-app/vite-vue-ts/src/components/InvestmentForm.vue
<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue';
import Modal from '@/components/Modal.vue';
import {
  type Investment,
  type InvestmentFormData,
  type InvestmentType,
  investmentFormSchema,
  toCents,
} from '@/schemas/investment';

const props = defineProps<{
  investment?: Investment;
  investmentTypes: InvestmentType[];
}>();

const emit = defineEmits<{
  submit: [investment: Investment];
  close: [];
}>();

const categoryLabels: Record<Investment['category'], string> = {
  'Fixed Income': 'Renda Fixa',
  'Variable Income': 'Renda Variavel',
};

const todayISO = new Date().toISOString().split('T')[0];

const formatCents = (cents: number) =>
  (cents / 100).toLocaleString('pt-BR', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

const defaultType = computed(() => props.investmentTypes[0]);
const form = reactive<InvestmentFormData>({
  name: props.investment?.name ?? '',
  typeId: props.investment?.typeId ?? defaultType.value?.id ?? '',
  broker: props.investment?.broker ?? '',
  amountCents: props.investment?.amount ?? 0,
  yield: props.investment?.yield ?? '',
  investedDate: props.investment?.investedDate ?? todayISO,
  dueDate: props.investment?.dueDate ?? '',
});
const amountDisplay = ref(props.investment ? formatCents(props.investment.amount) : '');
const errors = reactive<Record<keyof InvestmentFormData, string | null>>({
  name: null,
  typeId: null,
  broker: null,
  amountCents: null,
  yield: null,
  investedDate: null,
  dueDate: null,
});

const selectedType = computed(
  () => props.investmentTypes.find((type) => type.id === form.typeId) ?? defaultType.value,
);

watch(defaultType, (type) => {
  if (!form.typeId && type) {
    form.typeId = type.id;
  }
});

const clearErrors = () => {
  for (const key of Object.keys(errors) as Array<keyof InvestmentFormData>) {
    errors[key] = null;
  }
};

const handleAmountInput = (event: Event) => {
  const input = event.target as HTMLInputElement;
  const digits = input.value.replace(/\D/g, '');
  const cents = Number.parseInt(digits || '0', 10);
  form.amountCents = cents;
  amountDisplay.value = formatCents(cents);
};

const handleSubmit = () => {
  clearErrors();
  const parsed = investmentFormSchema.safeParse({ ...form });

  if (!parsed.success) {
    for (const issue of parsed.error.issues) {
      const field = issue.path[0] as keyof InvestmentFormData | undefined;
      if (field && field in errors) {
        errors[field] = issue.message;
      }
    }
    return;
  }

  if (!selectedType.value) return;

  emit('submit', {
    id: props.investment?.id ?? crypto.randomUUID(),
    name: parsed.data.name,
    typeId: parsed.data.typeId,
    broker: parsed.data.broker,
    amount: toCents(parsed.data.amountCents),
    yield: parsed.data.yield || undefined,
    category: selectedType.value.category,
    investedDate: parsed.data.investedDate,
    dueDate: parsed.data.dueDate || null,
  });
};
</script>

<template>
  <Modal :title="investment ? 'Editar investimento' : 'Novo investimento'" @close="emit('close')">
    <form class="space-y-4" @submit.prevent="handleSubmit">
      <div>
        <label for="investment-name" class="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-500">
          Nome
        </label>
        <input
          id="investment-name"
          v-model="form.name"
          class="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm text-slate-900 placeholder:text-slate-400 focus:border-sky-400 focus:ring-2 focus:ring-sky-200 focus:outline-none"
          placeholder="Ex: Tesouro IPCA+ 2045"
          :aria-invalid="Boolean(errors.name)"
        />
        <p v-if="errors.name" class="mt-1 text-xs text-red-500">{{ errors.name }}</p>
      </div>

      <div class="grid gap-4 sm:grid-cols-2">
        <div>
          <label for="investment-type" class="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-500">
            Tipo
          </label>
          <select
            id="investment-type"
            v-model="form.typeId"
            class="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm text-slate-900 focus:border-sky-400 focus:ring-2 focus:ring-sky-200 focus:outline-none"
            :aria-invalid="Boolean(errors.typeId)"
          >
            <option v-for="type in investmentTypes" :key="type.id" :value="type.id">
              {{ type.name }}
            </option>
          </select>
          <p v-if="errors.typeId" class="mt-1 text-xs text-red-500">{{ errors.typeId }}</p>
        </div>

        <div>
          <label for="investment-category" class="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-500">
            Categoria
          </label>
          <input
            id="investment-category"
            :value="selectedType ? categoryLabels[selectedType.category] : ''"
            readonly
            class="h-10 w-full rounded-lg border border-slate-100 bg-slate-100 px-3 text-sm text-slate-500"
          />
        </div>
      </div>

      <div class="grid gap-4 sm:grid-cols-2">
        <div>
          <label for="investment-broker" class="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-500">
            Corretora
          </label>
          <input
            id="investment-broker"
            v-model="form.broker"
            class="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm text-slate-900 placeholder:text-slate-400 focus:border-sky-400 focus:ring-2 focus:ring-sky-200 focus:outline-none"
            placeholder="Ex: XP Investimentos"
            :aria-invalid="Boolean(errors.broker)"
          />
          <p v-if="errors.broker" class="mt-1 text-xs text-red-500">{{ errors.broker }}</p>
        </div>

        <div>
          <label for="investment-amount" class="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-500">
            Valor (R$)
          </label>
          <input
            id="investment-amount"
            :value="amountDisplay"
            inputmode="numeric"
            class="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm text-slate-900 placeholder:text-slate-400 focus:border-sky-400 focus:ring-2 focus:ring-sky-200 focus:outline-none"
            placeholder="0,00"
            :aria-invalid="Boolean(errors.amountCents)"
            @input="handleAmountInput"
          />
          <p v-if="errors.amountCents" class="mt-1 text-xs text-red-500">{{ errors.amountCents }}</p>
        </div>
      </div>

      <div>
        <label for="investment-yield" class="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-500">
          Rendimento
          <span class="font-normal normal-case text-slate-400">(opcional - ex: IPCA + 5%, 110% CDI, 100% Selic, 15%)</span>
        </label>
        <input
          id="investment-yield"
          v-model="form.yield"
          class="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm text-slate-900 placeholder:text-slate-400 focus:border-sky-400 focus:ring-2 focus:ring-sky-200 focus:outline-none"
          placeholder="Ex: 100% Selic"
          :aria-invalid="Boolean(errors.yield)"
        />
        <p v-if="errors.yield" class="mt-1 text-xs text-red-500">{{ errors.yield }}</p>
      </div>

      <div class="grid gap-4 sm:grid-cols-2">
        <div>
          <label for="investment-invested-date" class="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-500">
            Data de aporte
          </label>
          <input
            id="investment-invested-date"
            v-model="form.investedDate"
            type="date"
            class="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm text-slate-900 focus:border-sky-400 focus:ring-2 focus:ring-sky-200 focus:outline-none"
            :aria-invalid="Boolean(errors.investedDate)"
          />
          <p v-if="errors.investedDate" class="mt-1 text-xs text-red-500">{{ errors.investedDate }}</p>
        </div>

        <div>
          <label for="investment-due-date" class="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-500">
            Vencimento <span class="font-normal normal-case text-slate-400">(opcional)</span>
          </label>
          <input
            id="investment-due-date"
            v-model="form.dueDate"
            type="date"
            class="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm text-slate-900 focus:border-sky-400 focus:ring-2 focus:ring-sky-200 focus:outline-none"
          />
        </div>
      </div>

      <div class="flex justify-end gap-3 pt-2">
        <button
          type="button"
          class="h-10 rounded-full border border-slate-300 bg-white px-5 text-sm font-semibold text-slate-700 hover:border-slate-400"
          @click="emit('close')"
        >
          Cancelar
        </button>
        <button
          type="submit"
          :disabled="!selectedType"
          class="h-10 rounded-full bg-sky-600 px-5 text-sm font-semibold text-white shadow-sm hover:bg-sky-500 disabled:bg-slate-300"
        >
          {{ investment ? 'Salvar' : 'Cadastrar' }}
        </button>
      </div>
    </form>
  </Modal>
</template>
