// classroom/react/invest-app/src/components/Navbar.tsx
'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Eye, EyeOff, LogIn, LogOut, UserPlus } from 'lucide-react';
import { useVisibility } from '@/stores/visibility';
import { useAuth } from '@/stores/auth';

export default function Navbar() {
  const { showValues, handleToggleShowValues } = useVisibility();
  const { user, logout } = useAuth();
  const router = useRouter();
  const displayName =
    typeof user?.user_metadata.name === 'string'
      ? user.user_metadata.name
      : user?.email;

  const handleLogout = async () => {
    await logout();
    router.replace('/login');
  };

  if (!user) {
    return (
      <header className="border-b border-slate-200 bg-white/90 backdrop-blur-sm">
        <nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-5 sm:px-6 lg:px-8">
          <Link
            href="/"
            className="text-lg font-semibold tracking-tight text-slate-900"
          >
            Invest App
          </Link>
          <div className="flex items-center gap-2">
            <Link
              href="/login"
              className="inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm font-semibold text-slate-600 transition hover:bg-slate-100 hover:text-slate-900"
            >
              <LogIn className="h-4 w-4" />
              Entrar
            </Link>
            <Link
              href="/register"
              className="inline-flex items-center gap-2 rounded-full bg-sky-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-sky-500"
            >
              <UserPlus className="h-4 w-4" />
              Cadastrar
            </Link>
          </div>
        </nav>
      </header>
    );
  }

  return (
    <header className="border-b border-slate-200 bg-white/90 backdrop-blur-sm">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-5 sm:px-6 lg:px-8">
        <Link
          href="/"
          className="text-lg font-semibold tracking-tight text-slate-900"
        >
          Invest App
        </Link>
        <div className="hidden items-center gap-8 md:flex">
          <Link
            href="/dashboard"
            className="text-sm font-medium text-slate-600 transition hover:text-slate-900"
          >
            Dashboard
          </Link>
          <Link
            href="/investments"
            className="text-sm font-medium text-slate-600 transition hover:text-slate-900"
          >
            Investimentos
          </Link>
        </div>
        <div className="flex items-center gap-2">
          {displayName && (
            <span className="hidden max-w-44 truncate text-sm font-medium text-slate-600 sm:inline">
              {displayName}
            </span>
          )}
          <button
            onClick={handleToggleShowValues}
            className="rounded-full p-2 text-slate-500 transition hover:bg-slate-100 hover:text-slate-900"
            aria-label={showValues ? 'Ocultar valores' : 'Exibir valores'}
          >
            {showValues ? (
              <EyeOff className="h-5 w-5" />
            ) : (
              <Eye className="h-5 w-5" />
            )}
          </button>
          <button
            onClick={handleLogout}
            className="rounded-full p-2 text-slate-500 transition hover:bg-slate-100 hover:text-slate-900"
            aria-label="Sair"
          >
            <LogOut className="h-5 w-5" />
          </button>
        </div>
      </nav>
    </header>
  );
}

// angular/invest-app/src/app/shared/components/navbar/navbar.component.ts
import { Component, inject } from '@angular/core';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';
import {
  LucideEye,
  LucideEyeOff,
  LucideLogIn,
  LucideLogOut,
  LucideUserCircle,
  LucideUserPlus,
} from '@lucide/angular';
import { AuthService } from '../../../core/services/auth.service';
import { VisibilityService } from '../../../core/services/visibility.service';

@Component({
  selector: 'app-navbar',
  imports: [
    RouterLink,
    RouterLinkActive,
    LucideEye,
    LucideEyeOff,
    LucideLogIn,
    LucideLogOut,
    LucideUserCircle,
    LucideUserPlus,
  ],
  template: `
    <header class="topbar">
      <nav class="nav-container">
        <a routerLink="/" class="brand">Invest App</a>

        @if (auth.user()) {
          <div class="nav-links">
            <a routerLink="/dashboard" routerLinkActive="active-link">Dashboard</a>
            <a routerLink="/investments" routerLinkActive="active-link">Investimentos</a>
          </div>
        }

        <div class="nav-actions">
          @if (auth.user()) {
            <button
              type="button"
              class="icon-button"
              [attr.aria-label]="visibility.showValues() ? 'Ocultar valores' : 'Exibir valores'"
              (click)="visibility.toggleValues()"
            >
              @if (visibility.showValues()) {
                <svg lucideEyeOff size="20" />
              } @else {
                <svg lucideEye size="20" />
              }
            </button>

            <div class="account-pill">
              <svg lucideUserCircle size="18" />
              <span>{{ auth.displayName() }}</span>
            </div>
            <button type="button" class="button button-ghost danger" (click)="logout()">
              <svg lucideLogOut size="16" />
              Sair
            </button>
          } @else {
            <a routerLink="/login" class="button button-ghost">
              <svg lucideLogIn size="16" />
              Entrar
            </a>
            <a routerLink="/register" class="button button-primary">
              <svg lucideUserPlus size="16" />
              Cadastrar
            </a>
          }
        </div>
      </nav>
    </header>
  `,
})
export class NavbarComponent {
  protected readonly auth = inject(AuthService);
  protected readonly visibility = inject(VisibilityService);
  private readonly router = inject(Router);

  async logout() {
    await this.auth.logout();
    await this.router.navigateByUrl('/login');
  }
}
